// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pharmacy_Management___Sales_API.Configration;

#nullable disable

namespace Pharmacy_Management___Sales_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829081519_fd")]
    partial class fd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pharmacy_Management___Sales_API.Model.Categpres", b =>
                {
                    b.Property<int>("IdCategpres")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategpres"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCategpres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategpres");

                    b.ToTable("categpres");
                });

            modelBuilder.Entity("Pharmacy_Management___Sales_API.Model.Customer", b =>
                {
                    b.Property<int>("idCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCustomer");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("Pharmacy_Management___Sales_API.Model.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduct"));

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("IdCategpres")
                        .HasColumnType("int");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quinte")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("idDetalis")
                        .HasColumnType("int");

                    b.Property<int>("salesidSales")
                        .HasColumnType("int");

                    b.HasKey("IdProduct");

                    b.HasIndex("IdCategpres");

                    b.HasIndex("salesidSales");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Pharmacy_Management___Sales_API.Model.Sales", b =>
                {
                    b.Property<int>("idSales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSales"));

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethods")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int>("idCustomer")
                        .HasColumnType("int");

                    b.HasKey("idSales");

                    b.ToTable("sales");
                });

            modelBuilder.Entity("Pharmacy_Management___Sales_API.Model.User", b =>
                {
                    b.Property<int>("idUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expired")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pharmacy_Management___Sales_API.Model.Customer", b =>
                {
                    b.HasOne("Pharmacy_Management___Sales_API.Model.Sales", "sales")
                        .WithMany("customers")
                        .HasForeignKey("idCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sales");
                });

            modelBuilder.Entity("Pharmacy_Management___Sales_API.Model.Product", b =>
                {
                    b.HasOne("Pharmacy_Management___Sales_API.Model.Categpres", "categpres")
                        .WithMany("products")
                        .HasForeignKey("IdCategpres")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pharmacy_Management___Sales_API.Model.Sales", "sales")
                        .WithMany("Products")
                        .HasForeignKey("salesidSales")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categpres");

                    b.Navigation("sales");
                });

            modelBuilder.Entity("Pharmacy_Management___Sales_API.Model.Categpres", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Pharmacy_Management___Sales_API.Model.Sales", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("customers");
                });
#pragma warning restore 612, 618
        }
    }
}
